let DataPreparation = require("./DataPreparation.js");


let cate = ["laranja", "maçã", "banana"];

let input = [
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random()+100, z:Math.random(), w: cate[Math.floor(Math.random()*3)]},

  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]},
  {x:Math.random(),y:Math.random(), z:Math.random(), w: cate[Math.floor(Math.random()*3)]}

];

let d = new  DataPreparation(input);
console.log(d.data_keys);
console.log(d.data_values);
console.log(d.data_values.length);
console.log(d.limit_values);
